# Generated by Django 5.1.1 on 2024-11-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_menthod',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash on Delivery', 'Cash on Delivery')], default='Credit Card', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='store.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, help_text='e.g., Last 4 digits of the card', max_length=20, null=True),
        ),
    ]
